# Generated by Django 3.0.8 on 2020-10-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
